# Generated by Django 6.0.4 on 2026-04-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_id', models.CharField(help_text='PIC 9(11) — 11-digit numeric account identifier.', max_length=11, unique=True, verbose_name='Account ID')),
                ('acct_active_status', models.CharField(default='Y', help_text='PIC X(01) — Y=active, N=inactive.', max_length=1, verbose_name='Active Status')),
                ('acct_curr_bal', models.DecimalField(decimal_places=2, default=0, help_text='PIC S9(10)V99 — signed current balance.', max_digits=12, verbose_name='Current Balance')),
                ('acct_credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='PIC S9(10)V99 — credit limit.', max_digits=12, verbose_name='Credit Limit')),
                ('acct_cash_credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='PIC S9(10)V99 — cash advance credit limit.', max_digits=12, verbose_name='Cash Credit Limit')),
                ('acct_open_date', models.CharField(blank=True, default='', help_text='PIC X(10) — YYYY-MM-DD format.', max_length=10, verbose_name='Open Date')),
                ('acct_expiration_date', models.CharField(blank=True, default='', help_text='PIC X(10) — YYYY-MM-DD format.', max_length=10, verbose_name='Expiration Date')),
                ('acct_reissue_date', models.CharField(blank=True, default='', help_text='PIC X(10) — YYYY-MM-DD format.', max_length=10, verbose_name='Reissue Date')),
                ('acct_curr_cyc_credit', models.DecimalField(decimal_places=2, default=0, help_text='PIC S9(10)V99 — current cycle credit total.', max_digits=12, verbose_name='Current Cycle Credit')),
                ('acct_curr_cyc_debit', models.DecimalField(decimal_places=2, default=0, help_text='PIC S9(10)V99 — current cycle debit total.', max_digits=12, verbose_name='Current Cycle Debit')),
                ('acct_group_id', models.CharField(blank=True, default='', help_text='PIC X(10) — account group identifier.', max_length=10, verbose_name='Group ID')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='CardXref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xref_card_num', models.CharField(help_text='PIC X(16) — 16-digit card number.', max_length=16, verbose_name='Card Number')),
                ('xref_cust_id', models.CharField(help_text='PIC 9(09).', max_length=9, verbose_name='Customer ID')),
                ('xref_acct_id', models.CharField(help_text='PIC 9(11).', max_length=11, verbose_name='Account ID')),
            ],
            options={
                'verbose_name': 'Card Cross Reference',
                'verbose_name_plural': 'Card Cross References',
                'db_table': 'card_xref',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(help_text='PIC 9(09) — 9-digit numeric customer identifier.', max_length=9, unique=True, verbose_name='Customer ID')),
                ('cust_first_name', models.CharField(blank=True, default='', help_text='PIC X(25).', max_length=25, verbose_name='First Name')),
                ('cust_middle_name', models.CharField(blank=True, default='', help_text='PIC X(25).', max_length=25, verbose_name='Middle Name')),
                ('cust_last_name', models.CharField(blank=True, default='', help_text='PIC X(25).', max_length=25, verbose_name='Last Name')),
                ('cust_addr_line_1', models.CharField(blank=True, default='', help_text='PIC X(50).', max_length=50, verbose_name='Address Line 1')),
                ('cust_addr_line_2', models.CharField(blank=True, default='', help_text='PIC X(50).', max_length=50, verbose_name='Address Line 2')),
                ('cust_addr_line_3', models.CharField(blank=True, default='', help_text='PIC X(50) — city/locality.', max_length=50, verbose_name='City')),
                ('cust_addr_state_cd', models.CharField(blank=True, default='', help_text='PIC X(02) — US state code.', max_length=2, verbose_name='State Code')),
                ('cust_addr_country_cd', models.CharField(blank=True, default='', help_text='PIC X(03).', max_length=3, verbose_name='Country Code')),
                ('cust_addr_zip', models.CharField(blank=True, default='', help_text='PIC X(10).', max_length=10, verbose_name='ZIP Code')),
                ('cust_phone_num_1', models.CharField(blank=True, default='', help_text='PIC X(15) — format (NPA)NXX-XXXX.', max_length=15, verbose_name='Phone Number 1')),
                ('cust_phone_num_2', models.CharField(blank=True, default='', help_text='PIC X(15) — format (NPA)NXX-XXXX.', max_length=15, verbose_name='Phone Number 2')),
                ('cust_ssn', models.CharField(blank=True, default='', help_text='PIC 9(09) — 9-digit SSN (stored without dashes).', max_length=9, verbose_name='SSN')),
                ('cust_govt_issued_id', models.CharField(blank=True, default='', help_text='PIC X(20).', max_length=20, verbose_name='Government Issued ID')),
                ('cust_dob_yyyy_mm_dd', models.CharField(blank=True, default='', help_text='PIC X(10) — YYYY-MM-DD format.', max_length=10, verbose_name='Date of Birth')),
                ('cust_eft_account_id', models.CharField(blank=True, default='', help_text='PIC X(10).', max_length=10, verbose_name='EFT Account ID')),
                ('cust_pri_card_holder_ind', models.CharField(blank=True, default='', help_text='PIC X(01) — Y/N indicator.', max_length=1, verbose_name='Primary Card Holder')),
                ('cust_fico_credit_score', models.CharField(blank=True, default='', help_text='PIC 9(03) — 300-850 range.', max_length=3, verbose_name='FICO Credit Score')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
            },
        ),
    ]
