# Generated by Django 5.2.13 on 2026-04-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_id', models.CharField(help_text='ACCT-ID PIC 9(11)', max_length=11, unique=True)),
                ('acct_active_status', models.CharField(default='', help_text='ACCT-ACTIVE-STATUS PIC X(01)', max_length=1)),
                ('acct_curr_bal', models.DecimalField(decimal_places=2, default=0, help_text='ACCT-CURR-BAL PIC S9(10)V99', max_digits=12)),
                ('acct_credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='ACCT-CREDIT-LIMIT PIC S9(10)V99', max_digits=12)),
                ('acct_cash_credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='ACCT-CASH-CREDIT-LIMIT PIC S9(10)V99', max_digits=12)),
                ('acct_open_date', models.CharField(default='', help_text='ACCT-OPEN-DATE PIC X(10)', max_length=10)),
                ('acct_expiration_date', models.CharField(default='', help_text='ACCT-EXPIRAION-DATE PIC X(10)', max_length=10)),
                ('acct_reissue_date', models.CharField(default='', help_text='ACCT-REISSUE-DATE PIC X(10)', max_length=10)),
                ('acct_curr_cyc_credit', models.DecimalField(decimal_places=2, default=0, help_text='ACCT-CURR-CYC-CREDIT PIC S9(10)V99', max_digits=12)),
                ('acct_curr_cyc_debit', models.DecimalField(decimal_places=2, default=0, help_text='ACCT-CURR-CYC-DEBIT PIC S9(10)V99', max_digits=12)),
                ('acct_addr_zip', models.CharField(default='', help_text='ACCT-ADDR-ZIP PIC X(10)', max_length=10)),
                ('acct_group_id', models.CharField(default='', help_text='ACCT-GROUP-ID PIC X(10)', max_length=10)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(help_text='CARD-NUM PIC X(16)', max_length=16, unique=True)),
                ('card_acct_id', models.CharField(db_index=True, help_text='CARD-ACCT-ID PIC 9(11)', max_length=11)),
                ('card_cvv_cd', models.CharField(default='', help_text='CARD-CVV-CD PIC 9(03)', max_length=3)),
                ('card_embossed_name', models.CharField(default='', help_text='CARD-EMBOSSED-NAME PIC X(50)', max_length=50)),
                ('card_expiration_date', models.CharField(default='', help_text='CARD-EXPIRAION-DATE PIC X(10)', max_length=10)),
                ('card_active_status', models.CharField(default='', help_text='CARD-ACTIVE-STATUS PIC X(01)', max_length=1)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='CardXref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xref_card_num', models.CharField(help_text='XREF-CARD-NUM PIC X(16)', max_length=16, unique=True)),
                ('xref_cust_id', models.CharField(db_index=True, help_text='XREF-CUST-ID PIC 9(09)', max_length=9)),
                ('xref_acct_id', models.CharField(db_index=True, help_text='XREF-ACCT-ID PIC 9(11)', max_length=11)),
            ],
            options={
                'verbose_name': 'Card Cross-Reference',
                'verbose_name_plural': 'Card Cross-References',
                'db_table': 'card_xref',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(help_text='CUST-ID PIC 9(09)', max_length=9, unique=True)),
                ('cust_first_name', models.CharField(default='', help_text='CUST-FIRST-NAME PIC X(25)', max_length=25)),
                ('cust_middle_name', models.CharField(default='', help_text='CUST-MIDDLE-NAME PIC X(25)', max_length=25)),
                ('cust_last_name', models.CharField(default='', help_text='CUST-LAST-NAME PIC X(25)', max_length=25)),
                ('cust_addr_line_1', models.CharField(default='', help_text='CUST-ADDR-LINE-1 PIC X(50)', max_length=50)),
                ('cust_addr_line_2', models.CharField(default='', help_text='CUST-ADDR-LINE-2 PIC X(50)', max_length=50)),
                ('cust_addr_line_3', models.CharField(default='', help_text='CUST-ADDR-LINE-3 PIC X(50)', max_length=50)),
                ('cust_addr_state_cd', models.CharField(default='', help_text='CUST-ADDR-STATE-CD PIC X(02)', max_length=2)),
                ('cust_addr_country_cd', models.CharField(default='', help_text='CUST-ADDR-COUNTRY-CD PIC X(03)', max_length=3)),
                ('cust_addr_zip', models.CharField(default='', help_text='CUST-ADDR-ZIP PIC X(10)', max_length=10)),
                ('cust_phone_num_1', models.CharField(default='', help_text='CUST-PHONE-NUM-1 PIC X(15)', max_length=15)),
                ('cust_phone_num_2', models.CharField(default='', help_text='CUST-PHONE-NUM-2 PIC X(15)', max_length=15)),
                ('cust_ssn', models.CharField(default='', help_text='CUST-SSN PIC 9(09)', max_length=9)),
                ('cust_govt_issued_id', models.CharField(default='', help_text='CUST-GOVT-ISSUED-ID PIC X(20)', max_length=20)),
                ('cust_dob_yyyy_mm_dd', models.CharField(default='', help_text='CUST-DOB-YYYY-MM-DD PIC X(10)', max_length=10)),
                ('cust_eft_account_id', models.CharField(default='', help_text='CUST-EFT-ACCOUNT-ID PIC X(10)', max_length=10)),
                ('cust_pri_card_holder_ind', models.CharField(default='', help_text='CUST-PRI-CARD-HOLDER-IND PIC X(01)', max_length=1)),
                ('cust_fico_credit_score', models.CharField(default='', help_text='CUST-FICO-CREDIT-SCORE PIC 9(03)', max_length=3)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dalytran_id', models.CharField(help_text='DALYTRAN-ID PIC X(16)', max_length=16, unique=True)),
                ('dalytran_type_cd', models.CharField(default='', help_text='DALYTRAN-TYPE-CD PIC X(02)', max_length=2)),
                ('dalytran_cat_cd', models.CharField(default='', help_text='DALYTRAN-CAT-CD PIC 9(04)', max_length=4)),
                ('dalytran_source', models.CharField(default='', help_text='DALYTRAN-SOURCE PIC X(10)', max_length=10)),
                ('dalytran_desc', models.CharField(default='', help_text='DALYTRAN-DESC PIC X(100)', max_length=100)),
                ('dalytran_amt', models.DecimalField(decimal_places=2, default=0, help_text='DALYTRAN-AMT PIC S9(09)V99', max_digits=11)),
                ('dalytran_merchant_id', models.CharField(default='', help_text='DALYTRAN-MERCHANT-ID PIC 9(09)', max_length=9)),
                ('dalytran_merchant_name', models.CharField(default='', help_text='DALYTRAN-MERCHANT-NAME PIC X(50)', max_length=50)),
                ('dalytran_merchant_city', models.CharField(default='', help_text='DALYTRAN-MERCHANT-CITY PIC X(50)', max_length=50)),
                ('dalytran_merchant_zip', models.CharField(default='', help_text='DALYTRAN-MERCHANT-ZIP PIC X(10)', max_length=10)),
                ('dalytran_card_num', models.CharField(db_index=True, help_text='DALYTRAN-CARD-NUM PIC X(16)', max_length=16)),
                ('dalytran_orig_ts', models.CharField(default='', help_text='DALYTRAN-ORIG-TS PIC X(26)', max_length=26)),
                ('dalytran_proc_ts', models.CharField(default='', help_text='DALYTRAN-PROC-TS PIC X(26)', max_length=26)),
            ],
            options={
                'verbose_name': 'Daily Transaction',
                'verbose_name_plural': 'Daily Transactions',
                'db_table': 'daily_transaction',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(help_text='TRAN-ID PIC X(16)', max_length=16, unique=True)),
                ('tran_type_cd', models.CharField(default='', help_text='TRAN-TYPE-CD PIC X(02)', max_length=2)),
                ('tran_cat_cd', models.CharField(default='', help_text='TRAN-CAT-CD PIC 9(04)', max_length=4)),
                ('tran_source', models.CharField(default='', help_text='TRAN-SOURCE PIC X(10)', max_length=10)),
                ('tran_desc', models.CharField(default='', help_text='TRAN-DESC PIC X(100)', max_length=100)),
                ('tran_amt', models.DecimalField(decimal_places=2, default=0, help_text='TRAN-AMT PIC S9(09)V99', max_digits=11)),
                ('tran_merchant_id', models.CharField(default='', help_text='TRAN-MERCHANT-ID PIC 9(09)', max_length=9)),
                ('tran_merchant_name', models.CharField(default='', help_text='TRAN-MERCHANT-NAME PIC X(50)', max_length=50)),
                ('tran_merchant_city', models.CharField(default='', help_text='TRAN-MERCHANT-CITY PIC X(50)', max_length=50)),
                ('tran_merchant_zip', models.CharField(default='', help_text='TRAN-MERCHANT-ZIP PIC X(10)', max_length=10)),
                ('tran_card_num', models.CharField(db_index=True, help_text='TRAN-CARD-NUM PIC X(16)', max_length=16)),
                ('tran_orig_ts', models.CharField(default='', help_text='TRAN-ORIG-TS PIC X(26)', max_length=26)),
                ('tran_proc_ts', models.CharField(default='', help_text='TRAN-PROC-TS PIC X(26)', max_length=26)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_type', models.CharField(help_text='TRAN-TYPE PIC X(02)', max_length=2, unique=True)),
                ('tran_type_desc', models.CharField(default='', help_text='TRAN-TYPE-DESC PIC X(50)', max_length=50)),
            ],
            options={
                'verbose_name': 'Transaction Type',
                'verbose_name_plural': 'Transaction Types',
                'db_table': 'transaction_type',
            },
        ),
        migrations.CreateModel(
            name='UserSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_usr_id', models.CharField(help_text='SEC-USR-ID PIC X(08)', max_length=8, unique=True)),
                ('sec_usr_fname', models.CharField(default='', help_text='SEC-USR-FNAME PIC X(20)', max_length=20)),
                ('sec_usr_lname', models.CharField(default='', help_text='SEC-USR-LNAME PIC X(20)', max_length=20)),
                ('sec_usr_pwd', models.CharField(default='', help_text='SEC-USR-PWD — hashed, never plain text', max_length=128)),
                ('sec_usr_type', models.CharField(default='', help_text='SEC-USR-TYPE PIC X(01)', max_length=1)),
            ],
            options={
                'verbose_name': 'User Security',
                'verbose_name_plural': 'User Security Records',
                'db_table': 'user_security',
            },
        ),
        migrations.CreateModel(
            name='DisclosureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_acct_group_id', models.CharField(help_text='DIS-ACCT-GROUP-ID PIC X(10)', max_length=10)),
                ('dis_tran_type_cd', models.CharField(help_text='DIS-TRAN-TYPE-CD PIC X(02)', max_length=2)),
                ('dis_tran_cat_cd', models.CharField(help_text='DIS-TRAN-CAT-CD PIC 9(04)', max_length=4)),
                ('dis_int_rate', models.DecimalField(decimal_places=2, default=0, help_text='DIS-INT-RATE PIC S9(04)V99 — HUMAN REVIEW: hardcoded interest rate', max_digits=6)),
            ],
            options={
                'verbose_name': 'Disclosure Group',
                'verbose_name_plural': 'Disclosure Groups',
                'db_table': 'disclosure_group',
                'unique_together': {('dis_acct_group_id', 'dis_tran_type_cd', 'dis_tran_cat_cd')},
            },
        ),
        migrations.CreateModel(
            name='TranCatBal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trancat_acct_id', models.CharField(help_text='TRANCAT-ACCT-ID PIC 9(11)', max_length=11)),
                ('trancat_type_cd', models.CharField(help_text='TRANCAT-TYPE-CD PIC X(02)', max_length=2)),
                ('trancat_cd', models.CharField(help_text='TRANCAT-CD PIC 9(04)', max_length=4)),
                ('tran_cat_bal', models.DecimalField(decimal_places=2, default=0, help_text='TRAN-CAT-BAL PIC S9(09)V99', max_digits=11)),
            ],
            options={
                'verbose_name': 'Transaction Category Balance',
                'verbose_name_plural': 'Transaction Category Balances',
                'db_table': 'tran_cat_bal',
                'unique_together': {('trancat_acct_id', 'trancat_type_cd', 'trancat_cd')},
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_type_cd', models.CharField(help_text='TRAN-TYPE-CD PIC X(02)', max_length=2)),
                ('tran_cat_cd', models.CharField(help_text='TRAN-CAT-CD PIC 9(04)', max_length=4)),
                ('tran_cat_type_desc', models.CharField(default='', help_text='TRAN-CAT-TYPE-DESC PIC X(50)', max_length=50)),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
                'db_table': 'transaction_category',
                'unique_together': {('tran_type_cd', 'tran_cat_cd')},
            },
        ),
        migrations.CreateModel(
            name='TransactionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trnx_card_num', models.CharField(db_index=True, help_text='TRNX-CARD-NUM PIC X(16)', max_length=16)),
                ('trnx_id', models.CharField(help_text='TRNX-ID PIC X(16)', max_length=16)),
                ('trnx_type_cd', models.CharField(default='', help_text='TRNX-TYPE-CD PIC X(02)', max_length=2)),
                ('trnx_cat_cd', models.CharField(default='', help_text='TRNX-CAT-CD PIC 9(04)', max_length=4)),
                ('trnx_source', models.CharField(default='', help_text='TRNX-SOURCE PIC X(10)', max_length=10)),
                ('trnx_desc', models.CharField(default='', help_text='TRNX-DESC PIC X(100)', max_length=100)),
                ('trnx_amt', models.DecimalField(decimal_places=2, default=0, help_text='TRNX-AMT PIC S9(09)V99', max_digits=11)),
                ('trnx_merchant_id', models.CharField(default='', help_text='TRNX-MERCHANT-ID PIC 9(09)', max_length=9)),
                ('trnx_merchant_name', models.CharField(default='', help_text='TRNX-MERCHANT-NAME PIC X(50)', max_length=50)),
                ('trnx_merchant_city', models.CharField(default='', help_text='TRNX-MERCHANT-CITY PIC X(50)', max_length=50)),
                ('trnx_merchant_zip', models.CharField(default='', help_text='TRNX-MERCHANT-ZIP PIC X(10)', max_length=10)),
                ('trnx_orig_ts', models.CharField(default='', help_text='TRNX-ORIG-TS PIC X(26)', max_length=26)),
                ('trnx_proc_ts', models.CharField(default='', help_text='TRNX-PROC-TS PIC X(26)', max_length=26)),
            ],
            options={
                'verbose_name': 'Transaction Index',
                'verbose_name_plural': 'Transaction Indexes',
                'db_table': 'transaction_index',
                'unique_together': {('trnx_card_num', 'trnx_id')},
            },
        ),
    ]
